spring.application.name=OnlineReservationSystem
server.port=8080


spring.datasource.url=jdbc:postgresql://localhost:5432/online_reservation_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8

spring.web.resources.static-locations=classpath:/static/

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always

spring.mvc.view.prefix=
spring.mvc.view.suffix=

